# 用户配置文件

springboot:
  basedir: . # 项目创建目录, 默认. 命令行当前目录. 自定义需要填写绝对路径
  groupId: com.project
  artifactId: test
  version: 0.0.1-SNAPSHOT
  javaVersion: 11
  description: Demo project for spring boot

project:
  installed:
    autosb: 0.0.1